### admin 로그인
POST https://api.recordyslow.com/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password" : "1234"
}
> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}


### 주문 취소
POST https://api.recordyslow.com/admin/cancelOrder
Content-Type: application/json
Authorization: {{auth_token}}

{
  "impId": "imp_758537410183",
  "productOrderNumber": 2024052900887
}

### 송장 번호 설정
PATCH https://api.recordyslow.com/admin/orders/17122490070512/trackingNumber
Content-Type: application/json
Authorization: {{auth_token}}

{
  "trackingNumber": "684435159956"
}

### 관리자 주문 조회
GET http://localhost:8080/admin/orders?page=0&size=20
Content-Type: application/json
Authorization: {{auth_token}}

### 상품 삭제 테스트
DELETE http://localhost:8080/admin/product/3
Authorization: {{auth_token}}


### 카테고리 생성
POST http://localhost:8080/admin/category
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "관리자 카테고리"
}


### 마켓 생성
POST http://localhost:8080/admin/market
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "쓰레기 값 마켓",
  "startDate": "2023-09-20",
  "startHour": "12",
  "startMinute": "0",
  "startSecond": "0",
  "description": "테스트용 쓰레기값 마켓"
}

### 마켓 이미지 추가
POST http://localhost:8080/admin/market/4/images
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="market1.png"

< img/market1.png
--WebAppBoundary--
Content-Disposition: form-data; name="images"; filename="market2.png"

< img/market2.png
--WebAppBoundary--

Content-Disposition: form-data; name="images"; filename="market3.png"

< img/market3.png
--WebAppBoundary--

Content-Disposition: form-data; name="images"; filename="market4.png"

< img/market4.png
--WebAppBoundary--

Content-Disposition: form-data; name="images"; filename="market5.png"

< img/market5.png
--WebAppBoundary--
#Content-Disposition: form-data; name="images"; filename="market6.png"
#
#< img/market6.png
#--WebAppBoundary--
#
#Content-Disposition: form-data; name="images"; filename="market6.png"
#
#< img/market6.png
#--WebAppBoundary--
#
#Content-Disposition: form-data; name="images"; filename="market7.png"
#
#< img/market7.png
#--WebAppBoundary--


### 이벤트 생성
POST http://localhost:8080/admin/event
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "쓰레기값 이벤트",
  "startDate": "2023-09-20",
  "startHour": "12",
  "startMinute": "0",
  "startSecond": "0",
  "endDate": "2023-10-01",
  "endHour": "12",
  "endMinute": "0",
  "endSecond": "0",
  "description": "테스트용 쓰레기값 이벤트"
}

### 이벤트 이미지 추가
POST http://localhost:8080/admin/event/2/images
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="event1.png"

< img/event1.png
--WebAppBoundary--
Content-Disposition: form-data; name="images"; filename="event2.png"

< img/event2.png
--WebAppBoundary--



### 상품 등록
POST https://rastledev.site/admin/product
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "상품1",
  "price": 100000,
  "discountPrice": 10,
  "bundleId": 19,
  "categoryId": 20,
  "productColor": {
    "productColors": [
      {
        "color": "blue",
        "sizes": [
          {
            "size": "M",
            "count": 1
          },
          {
            "size": "L",
            "count": 10
          }
        ]
      },
      {
        "color": "red",
        "sizes": [
          {
            "size": "M",
            "count": 1
          },
          {
            "size": "L",
            "count": 10
          }
        ]
      }

    ]
  },
  "displayOrder": 1000,
  "visible": true
}


### 상품 메인 썸네일 이미지 등록
POST http://localhost:8080/admin/product/16/mainThumbnail
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="mainThumbnail"; filename="thumbnail9.png"

< img/market5.png
--WebAppBoundary--


### 상품 서브 썸네일 이미지 등록
POST http://localhost:8080/admin/product/16/subThumbnail
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="subThumbnail"; filename="thumbnail10.png"

< img/thumbnail6.png
--WebAppBoundary--

### 상품 메인 이미지 등록
POST https://rastledev.site/admin/product/60/mainImages
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="mainImages"; filename="thumbnail3.png"

< img/thumbnail3.png
--WebAppBoundary--
Content-Disposition: form-data; name="mainImages"; filename="thumbnail4.png"

< img/thumbnail4.png
--WebAppBoundary--


### 상품 상세 이미지 등록
POST https://rastledev.site/admin/product/60/detailImages
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="detailImages"; filename="thumbnail2.png"

< img/thumbnail2.png
--WebAppBoundary--
Content-Disposition: form-data; name="detailImages"; filename="thumbnail1.png"

< img/thumbnail1.png
--WebAppBoundary--


### 상품 메인 이미지 업데이트
PUT https://rastledev.site/admin/product/60/mainImages
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="mainImages"; filename="thumbnail3.png"

< img/thumbnail3.png
--WebAppBoundary--
Content-Disposition: form-data; name="mainImages"; filename="thumbnail4.png"

< img/thumbnail4.png
--WebAppBoundary--


### 상품 상세 이미지 업데이트
PUT https://rastledev.site/admin/product/60/detailImages
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="detailImages"; filename="thumbnail2.png"

< img/thumbnail2.png
--WebAppBoundary--
Content-Disposition: form-data; name="detailImages"; filename="thumbnail1.png"

< img/thumbnail1.png
--WebAppBoundary--