### admin 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password" : "1234"
}
> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}


### 카테고리 생성
POST http://localhost:8080/admin/category
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "관리자 카테고리"
}

