### 멤버 회원가입
POST https://rastledev.site/auth/signup
Content-Type: application/json

{
  "email": "testest2@email.com",
  "password": "12341234@",
  "username": "qwerqwer",
  "phoneNumber": "01012541534"
}

### 멤버 로그인
POST https://rastledev.site/auth/login
Content-Type: application/json

{
  "email": "testest2@email.com",
  "password": "12341234@"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}



### 로그인한 멤버 정보 조회
GET http://localhost:8080/member
Content-Type: application/json
Authorization: {{auth_token}}