### 멤버 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "testest21@email.com",
  "password": "12341234@",
  "username": "qwerqwer",
  "phoneNumber": "01012541534"
}

### 멤버 로그인
POST https://api.recordyslow.com/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "a123456!"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}



### 로그인한 멤버 정보 조회
GET http://localhost:8080/member
Content-Type: application/json
Authorization: {{auth_token}}