### 전체 상품 조회
GET https://api.recordyslow.com/product?page=0&size=20

### 상품 상세 조회
GET https://rastledev.site/product/17/detail

### 이벤트 상품 조회
GET https://api.recordyslow.com/product/event?page=0&size=10

### 인기 상품 조회
GET https://api.recordyslow.com/product/popular?page=0&size=20

### 로컬 상품 조회
GET http://localhost:8080/product?page=0&size=100&visible=TRUE&sort=soldCount,DESC

### 로컬 상세 조회
GET http://localhost:8080/product/48

### 이벤트 로컬 조회
GET http://localhost:8080/product/event?page=0&size=100&visible=TRUE&sort=displayOrder,DESC
