name: CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: write

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.APP_HOST }}
          username: ubuntu
          key: ${{ secrets.APP_PEM_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/rastle_backend:1.0.0
#            docker stop was
#            docker remove was
#            sh run_was.sh