name: deploy-sub

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: write

jobs:
  update_sub:
    runs-on: ubuntu-latest
    steps:
      - name: sub 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SUB_HOST }}
          username: ubuntu
          key: ${{ secrets.SUB_PEM_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/rastle_backend 
            bash deploy.sh